### ISSUE TITLE
Backlog Management tools

### ISSUE THREAD

**Issue by fffej** [red-gate/internal-tech-radar#10]
JIRA, Trello, workflowy.com - I'm sure others are in use?

**Comment by nyctef** [comment]
Github issues are fairly common - I think Gearset use them exclusively (with something like HuBoard to make it more trello-y?) and Compare uses them for some issues which are more directly related to code (eg tech debt) rather than being customer/support-facing stuff which goes in JIRA

**Comment by garethbragg** [comment]
Considering how much of a God-awful mess our Jira setup is, I'm not surprised this is a problem!

**Comment by fffej** [comment]
@garethbragg / @nyctef - I've created #15 to capture some of the things mentioned above. Feel free to merge if you think it captures our choices, but also disagree if not :)

**Comment by garethbragg** [comment]
I think that works. I've :+1:ed the PR.
