### ISSUE TITLE
Key retains title of a radar section with no contents

### ISSUE THREAD

**Issue by garethbragg** [red-gate/internal-tech-radar#14]
*Repro steps:*
* Remove all nodes from a section of the radar
* Refresh the chart

*Expected result:*
* No nodes are shown in the section we cleared out
* The header for that section ("Explore", etc. doesn't show for that section of the chart

*Actual result:*
The header is still shown int he key, with no nodes beneath it

**Comment by fffej** [comment]
See PR #33
