### ISSUE TITLE
Add HockeyApp into investigation?

### ISSUE THREAD

**Issue by alastairs** [red-gate/internal-tech-radar#22]
It looks to fill a similar need to Raygun/Smart Assembly; it might be more mobile-focussed, though. It's run as a startup, but is actually a Microsoft product. https://hockeyapp.net/features/

**Comment by fffej** [comment]
Thanks @alastairs, that's a really good point - we haven't covered any of the error reporting tools/libraries (I reckon it's a tool, it's not just the code to consider, but the analysis/integrations).

My thoughts on things to add would be
- SmartAssembly
- Raygun
- Hockey App (thank you!)

Anything else we should add?
Is there anything else we should consider?

**Comment by alastairs** [comment]
I agree that it's a tool. 

There may be a parallel thing for telemetry (although maybe PFUR just does this for us and we don't need to do any more on this); things like New Relic, Application Insights, etc.

**Comment by fffej** [comment]
Issues closed as a result of PR #32
